declare module 'js-md5'
declare module 'qs'
declare module 'nprogress'
declare module 'element-plus/dist/locale/zh-cn.mjs'
declare module 'three'
declare module 'three/examples/jsm/controls/OrbitControls'
